WebExperience.Test/Pages/Account/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json.Serialization;
using System.Text.Json;

namespace WebExperience.Test.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly IHttpClientFactory _ClientFactory;

        [BindProperty] 
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required] [EmailAddress] public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Required] public bool RememberMe { get; set; }
        }

        public LoginModel(IHttpClientFactory clientFactory)
        {
            _ClientFactory = clientFactory;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostRedirectToRegister()
        {
            return RedirectToPage("RegisterUser");
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var client = _ClientFactory.CreateClient();
                var req = new HttpRequestMessage(HttpMethod.Post, "http://localhost:8080/api/account/signin/" + Input.Email + "/" + Input.Password + "/" + Input.RememberMe);
                var response = await client.SendAsync(req);

                var responseStream = await response.Content.ReadAsStringAsync();
                var result = JsonSerializer.Deserialize<bool>(responseStream);

                if (result)
                {
                    var user = new IdentityUser(Input.Email);
                    var userContent = new StringContent(JsonSerializer.Serialize(user), Encoding.UTF8, "application/json");
                    var signInResult = await client.PostAsync("http://localhost:8080/api/account/signin", userContent);

                    if (signInResult.IsSuccessStatusCode)
                    {
                        return RedirectToPage("/Asset/AssetList");
                    }
                    else
                    {
                        ModelState.AddModelError("", signInResult.ToString());
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Unable to login. Please check username and password.");
                }
            }

            return null;
        }
    }
}

WebExperience.Test/Pages/Account/RegisterUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace WebExperience.Test.Pages.Account
{
    public class RegisterUserModel : PageModel
    {
        private readonly IHttpClientFactory _ClientFactory;

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required] [EmailAddress] public string Email { get; set; }

            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Confirm Password")]
            [Compare("Password", ErrorMessage = "Confirmation password is not matched.")]
            public string ConfirmPassword { get; set; }
        }

        public RegisterUserModel(IHttpClientFactory clientFactory)
        {
            _ClientFactory = clientFactory;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var client = _ClientFactory.CreateClient();
                var req = new HttpRequestMessage(HttpMethod.Post, "http://localhost:8080/api/account/register/" + Input.Email + "/" + Input.Password);
                var response = await client.SendAsync(req);

                if (response.IsSuccessStatusCode)
                {
                    var responseStream = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<IdentityResult>(responseStream);

                    if (!result.Errors.Any())
                    {
                        var user = new IdentityUser(Input.Email);
                        var userContent = new StringContent(JsonConvert.SerializeObject(user), Encoding.UTF8, "application/json");
                        var signInResult = await client.PostAsync("http://localhost:8080/api/account/signin", userContent);

                        if (signInResult.IsSuccessStatusCode)
                        {
                            return RedirectToPage("/Asset/AssetList");
                        }
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError("", error.Description);
                        }
                    }
                }
            }

            return null;
        }
    }
}

WebExperience.Test/Pages/Account/Login.cshtml
@page
@model WebExperience.Test.Pages.Account.LoginModel
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.Password"></label>
                <input asp-for="Input.Password" class="form-control" />
                <span asp-validation-for="Input.Password"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.RememberMe"></label>
                <input asp-for="Input.RememberMe" class="form-check" />
                <span asp-validation-for="Input.RememberMe"></span>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
            <input type="submit" class="btn btn-primary" value="Sign up" asp-page-handler="RedirectToRegister" />
        </form>
    </div>
</div>

WebExperience.Test/Pages/Account/RegisterUser.cshtml
@page
@model RegisterUserModel
@{
    ViewData["Title"] = "Register New User";
}

<h1>User Registration</h1>
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Input.Email"></label>
                <input asp-for="Input.Email" class="form-control" />
                <span asp-validation-for="Input.Email"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.Password"></label>
                <input asp-for="Input.Password" class="form-control" />
                <span asp-validation-for="Input.Password"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.ConfirmPassword"></label>
                <input asp-for="Input.ConfirmPassword" class="form-control" />
                <span asp-validation-for="Input.ConfirmPassword"></span>
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>